a:
  - 0
  - 0
  - 256
  - 0
  - 0
  - 0
  - 0  
d:
  - 0
  - 240.5
  - 0
  - 0
  - 210
  - 0
  - 172.5
theta:
  - 0
  - 0
  - 90
  - 90
  - 0
  - 0
  - 0
alpha:
  - 0
  - 90
  - 0
  - 90
  - -90
  - 90
  - 0
# alpha:
#   - 0
#   - 0
#   - 90
#   - 0
#   - 90
#   - -90
#   - 90
